// 종합평가 관련 공통 타입 정의

// 자동 생성된 텍스트 타입
export interface AutoGeneratedText {
    main_category_id: number;
    category_name: string;
    auto_generated_texts: string[];
    final_content: string | null;
}

// 최종 평가 응답 타입
export interface FinalEvaluationResponse {
    student_id: number;
    student_name: string;
    category_evaluations: AutoGeneratedText[];
    overall_evaluation: string | null;
}

// 전체 평가 업데이트 파라미터 타입
export interface UpdateOverallEvaluationParams {
    studentId: number;
    overallEvaluation: string;
}

// 카테고리 평가 업데이트 파라미터 타입
export interface UpdateCategoryEvaluationParams {
    studentId: number;
    mainCategoryId: number;
    evaluationContent: string;
    isFinal?: boolean;
}

export interface OverallEvaluationResponse {
    student_id: number;
    overall_content: string | null;
    overall_evaluation_id: number;
    created_at: string;
    updated_at: string;
}
